name: "OZ - Land Claim"
main: de.omegazirkel.risingworld.LandClaim
version: 0.7.3
author: "Maik 'Devidian' Laschober"
team: "Omega Zirkel"
description: "Claim your own property and protect it from other players"
license: N/A
website: N/A
loadorder: 1
